config/routes.rb
Rails.application.routes.draw do
=begin
  get 'authors/index'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/show'
  get 'authors/destroy'
  get 'estimates/index'
  get 'estimates/new'
  get 'estimates/create'
  get 'estimates/update'
  get 'estimates/show'
  get 'estimates/destroy'
=end

  root to: 'for_user/books#index'
  devise_for :users

  resources :estimates

  namespace :api do
    post 'user_token' => 'user_token#create'
    resources :books, only: [:index]
    resources :authors, only: [:index, :show], param: :name
    resources :categories, only: [:index], param: :title
  end

  namespace :admin do
    resources :authors, only: [:index, :show, :new, :create, :update, :destroy]
    resources :users, only: [:index, :show, :update]
    resources :bookings, only: [:index, :new, :update, :destroy]
    resources :books, only: [:index, :show, :new, :create, :update, :destroy] do
      resources :units, only: [:destroy]
    end
    post '/bookings/update_bookings_statuses', to: 'bookings#update_bookings_statuses', as: 'update_bookings_statuses'
    post '/bookings/update_booking_status', to: 'bookings#update_booking_status', as: 'update_booking_status'
    post '/books/:book_id/units/add_one', to: 'units#create_unit_for_book', as: 'add_unit_book'
    post '/books/:book_id/recovery', to: 'books#recovery', as: 'recovery_book'
    # post '/books/:book_id/units/delete_last', to: 'units#delete_last_unit_for_book', as: 'delete_unit_book'
  end
  namespace :for_user do
    resources :authors, only: [:index, :show]
    resources :books, only: [:index, :show]
    resources :bookings, only: [:index, :create, :destroy]
    get '/bookings/show/taken/books', to: 'books#show_taken_books', as: 'show_taken_books'
    get '/bookings/show/readed/books', to: 'books#show_readed_books', as: 'readed_books'
  end
end

app/models/book.rb
class Book < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  belongs_to :author, counter_cache: :books_count
  belongs_to :category, counter_cache: :books_count
  belongs_to :language, counter_cache: :books_count
  has_many :units, dependent: :destroy
  has_many :bookings, through: :units
  has_many :estimates, dependent: :destroy
  has_many :users, through: :estimates


  validates :title, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :year, numericality: {only_integer: true,
                                  greater_than: 1000,
                                  less_than: Time.current.year + 1}

  include Filterable

  scope :by_title, ->(by_title) {where(arel_table[:title].matches("%#{by_title}%"))}
  scope :by_language_ids, ->(by_language_ids) {where(arel_table[:language_id].in(by_language_ids))}
  scope :by_authors_ids, ->(by_authors_ids) {where(arel_table[:author_id].in(by_authors_ids))}
  scope :by_year, ->(by_year) {where(arel_table[:year].eq(by_year))}
  scope :by_history, ->(by_history) {where(arel_table[:in_history].eq(by_history))}
  scope :by_category_ids, ->(by_category_ids) do
    joins(:category).where(categories: {id: by_category_ids})
  end
  scope :by_category_title, ->(category_title) do
    joins(:category).where(categories: {title: category_title})
  end
  scope :by_author_name, ->(author_name) do
    joins(:author).where(authors: {name: author_name})
  end
  scope :by_title_or_name_for_author, ->(filtre_atribut) do
    author = Author.arel_table
    book = Book.arel_table
    joins(:author).where((author[:name].matches("%#{filtre_atribut}%")).or(book[:title].matches("%#{filtre_atribut}%")))
  end
end

app/controllers/admin/books_controller.rb
module Admin
  class BooksController < ApplicationController
    before_action :authenticate_user!, :user_admin!

    def index
      @languages = Language.all
      @categories = Category.all
      @authors = Author.all
      @years = Array.new(Time.now.year - 999) {|index| [(index + 1000).to_s, index + 1000]} << ['No filtre', '']
      @books = Book.filter(params.slice(:by_language_ids, :by_authors_ids, :by_category_ids, :by_year, :by_title_or_name_for_author))
                   .page params[:page]
      render 'admin/books/index', :locals => {:fbookupload => "yes"}

    end

    def show
      @book = Book.find(params[:id])
      @units = @book.units
      @units_owner_name = {}
      @units.each do |unit|
        @units_owner_name[unit] = unit.bookings.by_status(:taken).first.user.username unless unit.bookings.by_status(:taken).first.nil?
      end
      @free_units_count = Unit.unit_available(true, @book.id).count
      @taken_units_count = Unit.unit_available(false, @book.id).count
    end

    def new
      @book = if !params[:book_id].nil?
                Book.find(params[:book_id])
              else
                Book.new
              end
    end

    def create
      @book = Book.new(book_params)
      if @book.save
        @status = 'Book Create'
        @book = Book.new
      end
      render :new
    end

    def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        redirect_to admin_books_path
      else
        render :new
      end
    end
    def recovery
      @book = Book.find(params[:book_id])
      @book.in_history = false
      @book.save
      redirect_to admin_books_path
    end
    def destroy
      @book = Book.find_by(id: params[:id])
      if @book
        if @book.update(in_history: true)
          @book.units.update_all(in_history: true, updated_at: DateTime.now)
          @book.bookings.by_status(:expectation).destroy_all
          redirect_to admin_books_path
        end
      end
    end

    def user_admin!
      redirect_to root_path unless current_user.admin
    end

    def book_params
      params.require(:book).permit(:id, :title, :year,
                                   :language_id, :author_id, :category_id, :description, :image)
    end
  end
end

app/controllers/api/books_controller.rb
module Api
  class BooksController < BaseController
    def index
      @books = Book.filter(params.slice(:by_language_ids, :by_authors_ids, :by_category_ids, :by_year, :by_title_or_name_fo_author, :by_author_name, :by_category_title))
                   .page params[:page]
      render json: @books
    end
  end
end

app/controllers/for_user/books_controller.rb
module ForUser
  class BooksController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :authenticate_user!, on: [:index, :show]

    def index
      @languages = Language.all
      @categories = Category.all
      @authors = Author.all
      @years = Array.new(Time.now.year - 999) {|index| [(index + 1000).to_s, index + 1000]} << ['No filtre'.to_s, "" ]
      @books = Book.by_history(false).filter(params.slice(:by_language_ids, :by_authors_ids, :by_category_ids, :by_year, :by_title_or_name_for_author))
                   .page params[:page]
      @free_units_count = {}
      @books.each do |book|
        @free_units_count[book] = Unit.unit_available(true, book.id).count
      end
    end

    def show
      @book = Book.find(params[:id])
      @free_units_count = {}
      @free_units_count[@book] = Unit.unit_available(true, @book.id).count

      if Unit.unit_available(false, @book.id).count == @book.units_count
        order_bookings = Booking.booking_by_status_book_id(:taken, @book.id).order(end_booking: :desc)
        unless order_bookings.empty?
          @day_whan_this_book_by_able = ((order_bookings.first.end_booking - DateTime.current) / 86_400).to_i
        end
      end
      @review = Estimate.new
    end

    def show_taken_books
      @books_booking = {}
      bookings = current_user.bookings.by_status(:taken).page params[:page]
      @books = bookings.map {|booking| booking.unit.book}
      # костиляка страшна
      @books = Book.where(id: @books.map(&:id))
      @books = @books.page params[:page]
      bookings.each {|booking| @books_booking[booking.unit.book] = booking}
    end

    def show_readed_books
      @books = current_user.bookings.booking_by_status_user_id(:returned, current_user.id).map {|booking| booking.unit.book}
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/index.html.erb
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
<!-- Modal -->
<div class='row'>
  <div id='myModal' class='modal fade' role='dialog'>
    <div class='modal-dialog'>
      <!-- Modal content-->
      <div class='modal-content'>
        <div class='modal-header'>
          <button type='button' class='close' data-dismiss='modal'>&times;</button>
          <!--          <h4 class='modal-title'>Filter for books</h4>-->
          <h4 class='modal-title'>Фільтер для книг</h4>
        </div>
        <div class='modal-body'>
          <%= form_tag admin_books_path, method: :get do %>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <!--                    <a data-toggle='collapse' href='#collapse1'>Languages</a>-->
                    <a data-toggle='collapse' href='#collapse1'>Мови</a>
                  </h4>
                </div>
                <div id='collapse1' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @languages.each do |language| %>
                      <%#= check_box_tag 'by_language_ids[]', language.id , params[:by_language_ids] %>
                      <%= check_box_tag 'by_language_ids[]', language.id %>
                      <%= h language.language %>;
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <!--                    <a data-toggle='collapse' href='#collapse2'>Authors</a>-->
                    <a data-toggle='collapse' href='#collapse2'>Автори</a>
                  </h4>
                </div>
                <div id='collapse2' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @authors.each do |author| %>
                      <%= check_box_tag 'by_authors_ids[]', author.id %>
                      <%= h author.name %>;
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <!--                    <a data-toggle='collapse' href='#collapse3'>Categories</a>-->
                    <a data-toggle='collapse' href='#collapse3'>Категорії</a>
                  </h4>
                </div>
                <div id='collapse3' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @categories.all.each do |categories| %>
                      <%= check_box_tag 'by_category_ids[]', categories.id %>
                      <%= h categories.title %>;
                    <% end %>
                    <!-- <%#= collection_check_boxes(:by_language_ids, :by_language_ids, Language.all, :id, :language) do |c| %><br>
                      <%#= c.label { c.check_box + '  ' + c.text } %>
                    <%# end %>-->
                  </div>
                </div>
              </div>
            </div>
            <div class='row'>
              <div class='col-md-12' style="padding-bottom: 5px">
                <%= text_field_tag 'by_title_or_name_for_author', params[:by_title_or_name_for_author],
                                   # placeholder: 'code\name_title\name_author'
                                   placeholder: 'код\назва книги\ім\'я автора',
                                   class: 'form-control col-md-6',
                                   style: 'width: 220px' %>
              </div>
            </div>
            <div class='col-md-6'>
              <!--              <%#= label_tag(:year, 'Year of release') %><br>-->
              <%= label_tag(:year, 'Рік випуску') %><br>
              <%= select_tag :by_year, options_for_select(@years, @years.last[1]) %>
              <!--              <div><%#= submit_tag 'Save' %></div>-->
              <div><%= submit_tag 'Зберегти' %></div>
            </div>
          <% end %>
          <div class='modal-footer'>
            <!--          <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>-->
            <button type='button' class='btn btn-default' data-dismiss='modal'>Закрити</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->

<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default panel-table'>
      <div class='panel-heading'>
        <div class='row'>
          <div class='col col-md-3 col-md-offset-1'>
            <button type='button' class='btn btn-info btn-ms' data-toggle='modal' data-target='#myModal'>
              <!--              Filter-->
              Фільтр
            </button>
          </div>
          <div class='col col-md-5 '>
            <% unless @books.empty? %>
              <%= paginate @books, outer_window: 3, class: "pagination", style: "margin: 0px; padding: 0px" %>
            <% end %>
          </div>
          <div class='col col-md-3 '>
            <%#= link_to 'Create book', new_admin_book_path, class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Створити книгу', new_admin_book_path, class: 'btn btn-sm btn-primary' %>
          </div>
        </div>
      </div>
      <div class='panel-body table-responsive'>
        <table class='table table-striped table-bordered table-hover table-list'>
          <thead>
          <tr>
            <h1><%= @status %></h1>
          </tr>
          <tr>
            <!--              <th><em class='fa fa-cog'></em></th>-->
            <!--              <th class='hidden-xs'>ID</th>-->
            <!--              <th class='hidden-xs'>Copies</th>-->
            <!--              <th>Title</th>-->
            <!--              <th>Year of release</th>-->
            <!--              <th>Category</th>-->
            <!--              <th>Author</th>-->
            <!--              <th>Rating:</th>-->
            <!--              <th>Description</th>-->
            <th><em class='fa fa-cog'></em></th>
            <th class='hidden-xs'>ID</th>
            <th class='hidden-xs'>Копії ID</th>
            <th>Назва</th>
            <th>Рік випуску</th>
            <th>Категорія</th>
            <th>Автор</th>
            <th>Рейтинг:</th>
            <th>Опис</th>
          </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <% if book.in_history %>
                <td align='center'>
                <%= link_to admin_recovery_book_path(book_id: book.id), method: :post, class: ' btn btn-success fa fa-wrench' do %>
                <% end %>
                </td>
              <% else %>
                <td align='center'>
                  <%= link_to new_admin_book_path(book_id: book.id), class: ' btn btn-warning fa fa-pencil' do %>
                  <% end %>
                  <%= link_to admin_book_path(book), method: :delete, data: {confirm: 'Are you sure?'}, class: ' btn btn-danger fa fa-trash' do %>
                  <% end %>
                  <%= link_to admin_add_unit_book_path(book), method: :post, class: 'btn btn-success fa fa-plus' do %>
                  <% end %>
                  <%#= link_to admin_delete_unit_book_path(book), method: :post, data: {confirm: 'Are you sure?'}, class: ' btn btn-danger fa fa-minus-circle' do %>
                  <%# end %>
                </td>
              <% end %>
              <td>
                <%= link_to book.id, admin_book_path(book.id) %>
              </td>
              <td>
                <%= link_to book.units_count, admin_book_path(book.id) %>
              </td>
              <td>
                <%= link_to book.title, admin_book_path(book.id) %>
              </td>
              <td>
                <%= link_to book.year, admin_book_path(book.id) %>
              </td>
              <% unless book.category.nil? || book.category.title.nil? %>
                <td>
                  <%= link_to book.category.title, admin_book_path(book.id) %>
                </td>
              <% else %>
                <td>Category: not exist</td><br>
              <% end %>
              <% unless book.author.nil? || book.author.name.nil? %>
                <td>
                  <%= link_to book.author.name, admin_book_path(book.id) %>
                </td>
              <% else %>
                <td>Author: not exist</td><br>
              <% end %>
              <td>
                <%= book.rating %>
              </td>
              <% if book.description.length < 30 %>
                <td>
                  <%= link_to book.description, admin_book_path(book.id) %>
                </td>
              <% else %>
                <td>
                  <%= link_to book.description[0..30] + '...', admin_book_path(book.id) %>
                </td>
              <% end %>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/new.html.erb
<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
    <% if @book.errors.any? %>
      <div class='error_explanation'>
        <h4><%= pluralize(@book.errors.count, 'error') %></h4>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h4><%= @status %></h4>
    <%= form_for [:admin, @book] do |f| %>
      <div class='form-group'>
        <div class='row'>
          <div class='col-md-6'>
            <%#= label_tag(:title, 'Title for book') %>
            <%= label_tag(:title, 'Назва книги') %>
            <%= f.text_field :title, class: 'form-control', style: 'background-color: #44312e73' %><br>
          </div>
          <div class='col-md-6'>
<!--            <%#= label_tag(:year, 'Year of release') %><br>-->
            <%= label_tag(:year, 'Рік випуску') %><br>
            <%= select_year Date.today,{ :start_year => Time.now.year, :end_year => Time.now.year - 1000, :field_name => :year, :prefix => :book},{class:'select-css'}%>
          </div>
        </div>
<!--        <%#= label_tag(:language, 'Language of book') %><br>-->
        <%= label_tag(:language, 'Мова книги') %><br>
        <%= f.collection_select :language_id, Language.order(:language), :id, :language, {prompt: true} ,{class:'select-css'}%><br>
        <div class='row'>
          <div class='col-md-8'>
            <%#= label_tag(:description, 'Description of book') %>
            <%= label_tag(:description, 'Опис книги') %>
            <%= f.text_area :description, class: 'form-control',style: 'background-color: #44312e73' %><br>
          </div>
          <div class='col-md-4'>
            <div class='row '>
<!--              <%#= label_tag(:language, 'Author of book') %><br>-->
              <%= label_tag(:language, 'Автор книги') %><br>
              <div class='select-st'>
              <%= f.collection_select :author_id, Author.order(:name), :id, :name, {prompt: true} ,{class:'select-css'}%><br>
              </div>
            </div>
            <div class='row'>
<!--              <%#= label_tag(:language, 'Category of book') %><br>-->
              <%= label_tag(:language, 'Категорія книги') %><br>
              <%= f.collection_select :category_id, Category.order(:title), :id, :title,  {prompt: true} ,{class:'select-css'} %><br>
            </div>
            <div class='row'>
              <%= f.hidden_field :image, value: @book.cached_image_data %>
              <%= f.file_field :image %>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit 'Зберегти', class: ' form-control ', style: 'font-size: 18px;
                                                            color: #040202ed;
                                                            background-color: #5a3113cc;
                                                            border: 0px solid #ccc;
                                                            border-radius: 10px;'%>
    <% end %>
  </div>
</div>

app/views/admin/books/show.html.erb
<div class='row'>
  <div class='col-md-12 about ' style='background-color:#e0b575e0; border-radius: 7px; padding: 5px;border: solid; border-width: 3px;'>
    <div class='row about'>
      <div class="col-md-12">
        <div class='row '>
          <div class='col-md-12 '>
            <div class='row'>
              <div class='col-md-12'>
                <%= image_tag @book.image_url, class: "img-responsive" if @book.image_url %>
              </div>
            </div>
          </div>
        </div>
        <div class='row '>
          <div class='col-md-12  desc card'>
            <ul>
<!--              <li>Title:<%#= @book.title %></li>-->
<!--              <li>Year of release:<%#= @book.year %></li>-->
              <li>Назва:<%= @book.title %></li>
              <li>Рік випуску:<%= @book.year %></li>
              <% unless @book.author.nil? || @book.author.name.nil? %>
<!--                <li>Author:<%#= @book.author.name %></li>-->
                <li>Автор:<%= @book.author.name %></li>
              <% else %>
<!--                <li>Author: not exist</li><br>-->
                <li>Автор: не існує</li><br>
              <% end %>
<!--              <li>Rating:  <%#= @book.rating %></li>-->
              <li>Рейтинг:  <%= @book.rating %></li>
              <% unless @book.category.nil? || @book.category.title.nil? %>
<!--                <li>Category:<%#= @book.category.title %></li>-->
                <li>Категорія:<%= @book.category.title %></li>
              <% else %>
<!--                <li>Category: not exist</li><br>-->
                <li>Категоря: не існує</li><br>
              <% end %>
              <% unless @book.language.nil? || @book.language.language.nil? %>
<!--                <li>Language:<%#= @book.language.language %></li>-->
                <li>Мова:<%= @book.language.language %></li>
              <% else %>
<!--                <li>Language: not exist</li><br>-->
                <li>Мова: не існує</li><br>
              <% end %>
<!--              <li>Count of copies:<%#= @book.units_count %></li>-->
<!--              <li>Count of free: ДОРОБИТИ</li>-->
<!--              <li>Count of ordes: ДОРОБИТИ</li>-->
              <li>Кількість копій :<%= @book.units_count %></li>
              <li>Кількість вільних: <%= @free_units_count %></li>
              <li>Кількість зайнятих: <%= @taken_units_count %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class='row' style='background-color: #fcaf58a6; border-radius: 7px; margin: 8px; padding: 5px; border: groove; border-width: 7px;'>
      <p style='word-break: break-all;'><%= @book.description %></p>
    </div>
  </div>
</div>

<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
<div class='row' style='margin-top: 10px;'>
  <div class='col-md-12'>
    <div class='panel panel-default panel-table'>
      <div class='panel-heading'>
        <div class='row'>
          <div class='col col-md-6 col-md-offset-3'>
            <div style='text-align: center'>
<!--              <strong>-->
<!--                All unit for this books-->
<!--              </strong>-->
              <strong>
                Всі копії даної книги
              </strong>
            </div>
          </div>
        </div>
      </div>
      <% if current_user.admin %>
        <div class='panel-body table-responsive'>
          <table class='table table-striped table-bordered table-list'>
            <thead>
              <tr>
                <th><em class='fa fa-cog'></em></th>
                <th class='hidden-xs'>ID</th>
<!--                <th class='hidden-xs'>Available</th>-->
<!--                <th class='hidden-xs'>Owner</th>-->
                <th class='hidden-xs'>Наявність</th>
                <th class='hidden-xs'>Взята користувачем</th>
              </tr>
            </thead>
            <tbody>
              <% @units.each do |unit| %>
                <tr>
                  <td align='center'>
                    <%= link_to admin_book_unit_path(id: unit.id, book_id: @book.id), method: :delete, data: {confirm: 'Are you sure?'}, class: ' btn btn-danger fa fa-minus-circle' do %>
                    <% end %>
                  </td>
                  <td><%= unit.id %></td>
                  <td><%= unit.available %></td>
                  <% if unit.available %>
                    <td>Not have owner</td>
                  <% else %>
                    <td><%= @units_owner_name[unit] %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>