config/routes.rb
Rails.application.routes.draw do
=begin
  get 'authors/index'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/show'
  get 'authors/destroy'
  get 'estimates/index'
  get 'estimates/new'
  get 'estimates/create'
  get 'estimates/update'
  get 'estimates/show'
  get 'estimates/destroy'
=end

  root to: 'for_user/books#index'
  devise_for :users

  resources :estimates

  namespace :api do
    post 'user_token' => 'user_token#create'
    resources :books, only: [:index]
    resources :authors, only: [:index, :show], param: :name
    resources :categories, only: [:index], param: :title
  end

  namespace :admin do
    resources :authors, only: [:index, :show, :new, :create, :update, :destroy]
    resources :users, only: [:index, :show, :update]
    resources :bookings, only: [:index, :new, :update, :destroy]
    resources :books, only: [:index, :show, :new, :create, :update, :destroy] do
      resources :units, only: [:destroy]
    end
    post '/bookings/update_bookings_statuses', to: 'bookings#update_bookings_statuses', as: 'update_bookings_statuses'
    post '/bookings/update_booking_status', to: 'bookings#update_booking_status', as: 'update_booking_status'
    post '/books/:book_id/units/add_one', to: 'units#create_unit_for_book', as: 'add_unit_book'
    post '/books/:book_id/recovery', to: 'books#recovery', as: 'recovery_book'
    # post '/books/:book_id/units/delete_last', to: 'units#delete_last_unit_for_book', as: 'delete_unit_book'
  end
  namespace :for_user do
    resources :authors, only: [:index, :show]
    resources :books, only: [:index, :show]
    resources :bookings, only: [:index, :create, :destroy]
    get '/bookings/show/taken/books', to: 'books#show_taken_books', as: 'show_taken_books'
    get '/bookings/show/readed/books', to: 'books#show_readed_books', as: 'readed_books'
  end
end

app/models/book.rb
class Book < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  belongs_to :author, counter_cache: :books_count
  belongs_to :category, counter_cache: :books_count
  belongs_to :language, counter_cache: :books_count
  has_many :units, dependent: :destroy
  has_many :bookings, through: :units
  has_many :estimates, dependent: :destroy
  has_many :users, through: :estimates


  validates :title, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :year, numericality: {only_integer: true,
                                  greater_than: 1000,
                                  less_than: Time.current.year + 1}

  include Filterable

  scope :by_title, ->(by_title) {where(arel_table[:title].matches("%#{by_title}%"))}
  scope :by_language_ids, ->(by_language_ids) {where(arel_table[:language_id].in(by_language_ids))}
  scope :by_authors_ids, ->(by_authors_ids) {where(arel_table[:author_id].in(by_authors_ids))}
  scope :by_year, ->(by_year) {where(arel_table[:year].eq(by_year))}
  scope :by_history, ->(by_history) {where(arel_table[:in_history].eq(by_history))}
  scope :by_category_ids, ->(by_category_ids) do
    joins(:category).where(categories: {id: by_category_ids})
  end
  scope :by_category_title, ->(category_title) do
    joins(:category).where(categories: {title: category_title})
  end
  scope :by_author_name, ->(author_name) do
    joins(:author).where(authors: {name: author_name})
  end
  scope :by_title_or_name_for_author, ->(filtre_atribut) do
    author = Author.arel_table
    book = Book.arel_table
    joins(:author).where((author[:name].matches("%#{filtre_atribut}%")).or(book[:title].matches("%#{filtre_atribut}%")))
  end
end

app/controllers/admin/books_controller.rb
module Admin
  class BooksController < ApplicationController
    before_action :authenticate_user!, :user_admin!

    def index
      @languages = Language.all
      @categories = Category.all
      @authors = Author.all
      @years = Array.new(Time.now.year - 999) {|index| [(index + 1000).to_s, index + 1000]} << ['No filtre', '']
      @books = Book.filter(params.slice(:by_language_ids, :by_authors_ids, :by_category_ids, :by_year, :by_title_or_name_for_author))
                   .page params[:page]
      render 'admin/books/index', :locals => {:fbookupload => "yes"}

    end

    def show
      @book = Book.find(params[:id])
      @units = @book.units
      @units_owner_name = {}
      @units.each do |unit|
        @units_owner_name[unit] = unit.bookings.by_status(:taken).first.user.username unless unit.bookings.by_status(:taken).first.nil?
      end
      @free_units_count = Unit.unit_available(true, @book.id).count
      @taken_units_count = Unit.unit_available(false, @book.id).count
    end

    def new
      @book = if !params[:book_id].nil?
                Book.find(params[:book_id])
              else
                Book.new
              end
    end

    def create
      @book = Book.new(book_params)
      if @book.save
        @status = 'Book Create'
        @book = Book.new
      end
      render :new
    end

    def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        redirect_to admin_books_path
      else
        render :new
      end
    end
    def recovery
      @book = Book.find(params[:book_id])
      @book.in_history = false
      @book.save
      redirect_to admin_books_path
    end
    def destroy
      @book = Book.find_by(id: params[:id])
      if @book
        if @book.update(in_history: true)
          @book.units.update_all(in_history: true, updated_at: DateTime.now)
          @book.bookings.by_status(:expectation).destroy_all
          redirect_to admin_books_path
        end
      end
    end

    def user_admin!
      redirect_to root_path unless current_user.admin
    end

    def book_params
      params.require(:book).permit(:id, :title, :year,
                                   :language_id, :author_id, :category_id, :description, :image)
    end
  end
end

app/controllers/api/books_controller.rb
module Api
  class BooksController < BaseController
    def index
      @books = Book.filter(params.slice(:by_language_ids, :by_authors_ids, :by_category_ids, :by_year, :by_title_or_name_fo_author, :by_author_name, :by_category_title))
                   .page params[:page]
      render json: @books
    end
  end
end

app/controllers/for_user/authors_controller.rb
module ForUser
  class AuthorsController < ApplicationController
    def index
      @authors = Author.all.page params[:page]
    end

    def show
      @author = Author.find(params[:id])
    end
  end
end

app/controllers/for_user/bookings_controller.rb
module ForUser
  class BookingsController < ApplicationController
    before_action :authenticate_user!

    def index
      @bookings = current_user.bookings.page params[:page]
      @books_booking = {}
      @bookings.each {|booking| (@books_booking[booking] = booking.unit.book) if booking.unit}
    end

    def create
      if (current_user.bookings.by_status(:taken).count < 4 && !(current_user.bookings.by_status(:owed).count > 0) && Booking.booking_by_status_book_id("expectation",params[:book_id]).count < 1)
        booking = Booking.new
        free_units = Unit.unit_available(true, params[:book_id])
        booking[:start_booking] = DateTime.current + 4.days
        booking[:end_booking] = DateTime.current + 24.days
        unit = free_units.first
        booking.unit = unit
        booking.book_title = unit.book.title
        booking.author_name = unit.book.author.name
        booking.user = current_user
        booking[:code] = SecureRandom.hex(7)
        booking.save
      end
      redirect_to for_user_bookings_path
    end

    def destroy
      @booking = Booking.find_by(id: params[:id])
      if @booking && @booking.status == "expectation"
        @booking.destroy
        redirect_to for_user_bookings_path
      else
        redirect_to for_user_bookings_path
        return
      end
    end

  end
end

app/controllers/for_user/books_controller.rb
module ForUser
  class BooksController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :authenticate_user!, on: [:index, :show]

    def index
      @languages = Language.all
      @categories = Category.all
      @authors = Author.all
      @years = Array.new(Time.now.year - 999) {|index| [(index + 1000).to_s, index + 1000]} << ['No filtre'.to_s, "" ]
      @books = Book.by_history(false).filter(params.slice(:by_language_ids, :by_authors_ids, :by_category_ids, :by_year, :by_title_or_name_for_author))
                   .page params[:page]
      @free_units_count = {}
      @books.each do |book|
        @free_units_count[book] = Unit.unit_available(true, book.id).count
      end
    end

    def show
      @book = Book.find(params[:id])
      @free_units_count = {}
      @free_units_count[@book] = Unit.unit_available(true, @book.id).count

      if Unit.unit_available(false, @book.id).count == @book.units_count
        order_bookings = Booking.booking_by_status_book_id(:taken, @book.id).order(end_booking: :desc)
        unless order_bookings.empty?
          @day_whan_this_book_by_able = ((order_bookings.first.end_booking - DateTime.current) / 86_400).to_i
        end
      end
      @review = Estimate.new
    end

    def show_taken_books
      @books_booking = {}
      bookings = current_user.bookings.by_status(:taken).page params[:page]
      @books = bookings.map {|booking| booking.unit.book}
      # костиляка страшна
      @books = Book.where(id: @books.map(&:id))
      @books = @books.page params[:page]
      bookings.each {|booking| @books_booking[booking.unit.book] = booking}
    end

    def show_readed_books
      @books = current_user.bookings.booking_by_status_user_id(:returned, current_user.id).map {|booking| booking.unit.book}
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/for_user/books/index.html.erb
<div class='row' style='margin-bottom: 12px '>
  <div class='col col-md-3 '>
    <button type='button' class='btn btn-info btn-ms' data-toggle='modal' data-target='#myModal'>
      Фільтр
    </button>
  </div>
</div>
<div class='row'>
  <!-- Modal -->
  <div id='myModal' class='modal fade' role='dialog'>
    <div class='modal-dialog'>
      <!-- Modal content-->
      <div class='modal-content'>
        <div class='modal-header'>
          <button type='button' class='close' data-dismiss='modal'>&times;</button>
          <h4 class='modal-title'>Фільтр для книг</h4>
        </div>
        <div class='modal-body'>
          <%= form_tag for_user_books_path, method: :get do %>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <!--                    <a data-toggle='collapse' href='#collapse1'>Languages</a>-->
                    <a data-toggle='collapse' href='#collapse1'>Мови</a>
                  </h4>
                </div>
                <div id='collapse1' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @languages.each do |language| %>
                      <%= check_box_tag 'by_language_ids[]', language.id %>
                      <%= h language.language %>;
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <!--                    <a data-toggle='collapse' href='#collapse2'>Authors</a>-->
                    <a data-toggle='collapse' href='#collapse2'>Автори</a>
                  </h4>
                </div>
                <div id='collapse2' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @authors.each do |author| %>
                      <%= check_box_tag 'by_authors_ids[]', author.id %>
                      <%= h author.name %>;
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <!--                    <a data-toggle='collapse' href='#collapse3'>Categories</a>-->
                    <a data-toggle='collapse' href='#collapse3'>Категорії</a>
                  </h4>
                </div>
                <div id='collapse3' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @categories.all.each do |categories| %>
                      <%= check_box_tag 'by_category_ids[]', categories.id %>
                      <%= h categories.title %>;
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='row'>
              <div class='col-md-12' style="padding-bottom: 5px">
                <%= text_field_tag 'by_title_or_name_for_author', params[:by_title_or_name_for_author],
                                   # placeholder: 'code\name_title\name_author'
                                   placeholder: 'назва книги\ім\'я автора',
                                   class: 'form-control col-md-6',
                                   style: 'width: 220px' %>
              </div>
            </div>
            <div class='col-md-6'>
              <!--              <%#= label_tag(:year, 'Year of release') %><br>-->
              <%= label_tag(:year, 'Рік випуску') %><br>
              <%= select_tag :by_year, options_for_select(@years, @years.last[1]) %>
              <!--              <div><%#= submit_tag 'Save' %></div>-->
              <div><%= submit_tag 'Зберегти' %></div>
            </div>
          <% end %>
          <div class='modal-footer'>
            <button type='button' class='btn btn-default' data-dismiss='modal'>Закрити</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class='container-fluid cards-row'>
  <div class='row'>
    <% @books.each do |book| %>
      <div class='col-sm-6 col-md-4 article'>
        <div class='thumbnail' style='outline-style: solid; outline-radius: 7px; background-color: #ddaa68e6;  max-height: 300px; overflow-y: auto'>
          <%= image_tag book.image_url, class: "img-responsive" if book.image_url %>
          <div class='caption'
               <% if @free_units_count[book] > 0 %> style='border-radius: 7px;background-color: #28a745a6'
               <% else %>
               style='border-radius: 7px;background-color: #da7916b8'
               <% end %>
               >
            <h3>Tile Of Book:
              <td style='word-break: break-all;'><%= link_to book.title, for_user_book_path(book.id) %></td>
            </h3>
            <p class='card-description'>
              <strong>Рік випуску:<%= book.year %></strong><br>
              <% unless book.author.nil? || book.author.name.nil? %>
                <!--                <strong>Author:  <%#= book.author.name %></strong><br>-->
                <strong>Автор:  <%= book.author.name %></strong><br>
              <% else %>
                <!--                <strong>Author: not exist</strong><br>-->
                <strong>Автор: не існує</strong><br>
              <% end %>
              <% unless book.language.nil? || book.language.language.nil? %>
                <!--                <strong>Language:  <%#= book.language.language %></strong><br>-->
                <strong>Мова:  <%= book.language.language %></strong><br>
              <% else %>
                <!--                <strong>Language: not exist</strong><br>-->
                <strong>Мова: не існує</strong><br>
              <% end %>
              <% unless book.category.nil? || book.category.title.nil? %>
                <strong>Категорія:  <%= book.category.title %></strong><br>
              <% else %>
                <strong>Категорія: не існує</strong><br>
              <% end %>

              <!--              <strong>Rating:  <%#= book.rating %></strong><br>-->
              <!--              <strong>Count of Free:</strong> <%#= @free_units_count[book] %>\<%#= book.units_count %></p>-->
              <strong>Рейтинг:  <%= book.rating %></strong><br>
              <strong>Кількість вільних екземплярів:</strong> <%= @free_units_count[book] %>\<%= book.units_count %>
              <% unless current_user %>
                <!--              <p>If you want do order you should to autorize</p>-->
              <p>Якщо ви хочете замовити книгу вам потрібно авторизуватись</p>
            <% else %>
              <% if @free_units_count[book] > 0 %>
                <% if current_user.bookings.by_status(:taken).count < 4 %>
                  <% if current_user.bookings.by_status(:owed).count == 0 %>
                    <%= form_with url: for_user_bookings_path do |form| %>
                      <%= hidden_field_tag(:book_id, book.id) %>
                      <%#= form.submit 'Do order', class: 'btn btn-success fa fa-check fa-1' %>
                      <%= form.submit 'Зробити замовлення', class: 'btn btn-success fa fa-check fa-1' %>
                    <% end %>
                  <% else %>
                    <!--                    <p>You are debtor</p>-->
                    <p>Ви боржник</p>
                  <% end %>
                <% else %>
                  <!--                  <p>You have too much bookings</p>-->
                  <p>У вас за багато замовлень</p>
                <% end %>
              <% else %>
                <!--                <p>Not have free books</p>-->
                <p>Не має вільних екземплярів книги</p>
              <% end %>
            <% end %>
          </div>
          <%= @msg %>
        </div>
      </div>
    <% end %>
  </div>
  <nav class="navbar  navbar-bottom ">
    <div class="text-center">
      <% unless @books.empty? %>
        <%= paginate @books, outer_window: 3, class: "pagination" %>
      <% end %>
    </div>
  </nav>
</div>

app/views/for_user/books/show.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2  about ' style='background-color:#e0b575e0; border-radius: 7px; padding: 5px;border: solid; border-width: 3px;'>
    <div class='row about'>
      <div class="col-md-12">
        <div class='row'>
          <div class='col-md-12' style="margin-bottom: 5px">
            <%= image_tag @book.image_url, class: "img-responsive" if @book.image_url %>
          </div>
        </div>
        <div class='row desc card'>
          <div class='col-md-12'>
            <ul>
<!--              <li>Title:<%#= @book.title %></li>-->
<!--              <li>Year of release:<%#= @book.year %></li>-->
              <li>Назва:<%= @book.title %></li>
              <li>Рік випуску:<%= @book.year %></li>
              <% unless @book.author.nil? || @book.author.name.nil? %>
<!--                <li>Author:<%#= @book.author.name %></li>-->
                <li>Автор:<%= @book.author.name %></li>
              <% else %>
<!--                <li>Author: not exist</li><br>-->
                <li>Автор: не існує</li><br>
              <% end %>
              <% unless @book.category.nil? || @book.category.title.nil? %>
<!--                <li>Category:<%#= @book.category.title %></li>-->
                <li>Категорія:<%= @book.category.title %></li>
              <% else %>
<!--                <li>Category: not exist</li><br>-->
                <li>Категорія: не існує</li><br>
              <% end %>
              <% unless @book.language.nil? || @book.language.language.nil? %>
<!--                <li>Language:<%#= @book.language.language %></li>-->
                <li>Мова:<%= @book.language.language %></li>
              <% else %>
<!--                <li>Language: not exist</li><br>-->
                <li>Мова: не існує</li><br>
              <% end %>
<!--              <li>Count of copies:<%#= @book.units_count %></li>-->
<!--              <li>Count of free:<%#= @free_units_count[@book] %></li>-->
<!--              <li>Rating:  <%#= @book.rating %></li>-->
<!--              <li>Count of ordes:<%#= @book.units_count - @free_units_count[@book] %></li>-->
<!--              <li>Before this book be able days:<%#= @day_whan_this_book_by_able %></li>-->
              <li>Кількість копій:<%= @book.units_count %></li>
              <li>Кількість вільних екземплярів:<%= @free_units_count[@book] %></li>
              <li>Рейтинг:  <%= @book.rating %></li>
              <li>Кількість замовлених екземплятів:<%= @book.units_count - @free_units_count[@book] %></li>
              <li>Ймовірно книга буде доступна через:<%= @day_whan_this_book_by_able %> днів</li>
              <!--              TODO виправити це-->
              <% if user_signed_in?  %>
                <li>
                  <%= form_tag new_estimate_path, method: :get do %>
                    <%= hidden_field_tag 'book_id', @book.id %>
                    <%= submit_tag 'Додати оцінку', class: 'btn btn-sm btn-primary' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class='row' style='background-color: #fcaf58a6; border-radius: 7px; margin: 8px; padding: 5px; border: groove; border-width: 3px;'>
      <p style='word-break: break-all;'><%= @book.description %></p>
    </div>
  </div>
</div>

app/views/for_user/books/show_readed_books.html.erb
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default panel-table'>
      <div class='panel-heading'>
        <div class='row'>
          <div class='col col-md-6 text-right col-md-offset-3'>
            <div style='text-align: center'>
<!--              <strong>-->
<!--                Books that you read-->
<!--              </strong>-->
              <strong>
                Ваші прочитані книги
              </strong>
            </div>
          </div>
        </div>
      </div>
      <div class='panel-body'>
        <table class='table table-striped table-bordered table-list'>
          <thead>
            <tr>
<!--              <th>Title</th>-->
<!--              <th>Year of release</th>-->
<!--              <th>Catecory</th>-->
<!--              <th>Author</th>-->
<!--              <th>Description</th>-->
              <th>Назва</th>
              <th>Рік випуску</th>
              <th>Категорія</th>
              <th>Автор</th>
              <th>Опис</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to book.title, for_user_book_path(book.id) %></td>
                <td><%= link_to book.year, for_user_book_path(book.id) %></td>
                <% unless book.category.nil? || book.category.title.nil? %>
                  <td><%= link_to book.category.title, for_user_book_path(book.id) %></td>
                <% else %>
<!--                  <td>Category: not exist</td><br>-->
                  <td>Категорія: не існує</td><br>
                <% end %>
                <% unless book.author.nil? || book.author.name.nil? %>
                  <td><%= link_to book.author.name, for_user_author_path(book.author.id) %></td>
                <% else %>
<!--                  <td>Author: not exist</td><br>-->
                  <td>Автор: не існує</td><br>
                <% end %>
                <% if book.description.length < 30 %>
                  <td><%= link_to book.description, for_user_book_path(book.id) %></td>
                <% else %>
                  <td><%= link_to book.description[0..30] + '...', for_user_book_path(book.id) %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/for_user/books/show_taken_books.html.erb
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default panel-table'>
      <div class='panel-heading'>
        <div class='row'>
          <div class='col col-md-6 text-right col-md-offset-3'>
            <div style='text-align: center'>
              <strong>
                Взяті книги
              </strong>
            </div>
          </div>
        </div>
      </div>
      <div class='panel-body'>
        <table class='table table-striped table-bordered table-list'>
          <thead>
            <tr>
<!--              <th>Title</th>-->
<!--              <th>Year of release</th>-->
<!--              <th>Catecory</th>-->
<!--              <th>Author</th>-->
<!--              <th>Description</th>-->
<!--              <th>Start oreder this book:</th>-->
<!--              <th>End oreder this book:</th>-->
<!--              <th>before the end of the order days:</th>-->
              <th>Назва</th>
              <th>Рік випуску</th>
              <th>Категорія</th>
              <th>Автор</th>
              <th>Опис</th>
              <th>Початок замовлення цієї книги:</th>
              <th>Кінець замовлення цієї книги:</th>
              <th>До кінця замовлення залишилося:</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>

                <td><%= link_to book.title, for_user_book_path(book.id) %></td>
                <td><%= link_to book.year, for_user_book_path(book.id) %></td>
                <% unless book.category.nil? || book.category.title.nil? %>
                  <td><%= link_to book.category.title, for_user_book_path(book.id) %></td>
                <% else %>
<!--                  <td>Category: not exist</td><br>-->
                  <td>Категорії: не існує</td><br>
                <% end %>
                <% unless book.author.nil? || book.author.name.nil? %>
                  <td><%= link_to book.author.name, for_user_book_path(book.id) %></td>
                <% else %>
<!--                  <td>Author: not exist</td><br>-->
                  <td>Автор: не існує</td><br>
                <% end %>
                <% if book.description.length < 30 %>
                  <td><%= link_to book.description, for_user_book_path(book.id) %></td>
                <% else %>
                  <td><%= link_to book.description[0..30] + '...', for_user_book_path(book.id) %></td>
                <% end %>
                <td><%= @books_booking[book].start_booking %></td>
                <td><%= @books_booking[book].end_booking %></td>
                <td><%= ((@books_booking[book].end_booking - DateTime.current) / 86400).to_i %> днів</td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <% unless @books.empty? %>
              <%= paginate @books, outer_window: 3, class: "pagination" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>