config/routes.rb
Rails.application.routes.draw do
=begin
  get 'authors/index'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/show'
  get 'authors/destroy'
  get 'estimates/index'
  get 'estimates/new'
  get 'estimates/create'
  get 'estimates/update'
  get 'estimates/show'
  get 'estimates/destroy'
=end

  root to: 'for_user/books#index'
  devise_for :users

  resources :estimates

  namespace :api do
    post 'user_token' => 'user_token#create'
    resources :books, only: [:index]
    resources :authors, only: [:index, :show], param: :name
    resources :categories, only: [:index], param: :title
  end

  namespace :admin do
    resources :authors, only: [:index, :show, :new, :create, :update, :destroy]
    resources :users, only: [:index, :show, :update]
    resources :bookings, only: [:index, :new, :update, :destroy]
    resources :books, only: [:index, :show, :new, :create, :update, :destroy] do
      resources :units, only: [:destroy]
    end
    post '/bookings/update_bookings_statuses', to: 'bookings#update_bookings_statuses', as: 'update_bookings_statuses'
    post '/bookings/update_booking_status', to: 'bookings#update_booking_status', as: 'update_booking_status'
    post '/books/:book_id/units/add_one', to: 'units#create_unit_for_book', as: 'add_unit_book'
    post '/books/:book_id/recovery', to: 'books#recovery', as: 'recovery_book'
    # post '/books/:book_id/units/delete_last', to: 'units#delete_last_unit_for_book', as: 'delete_unit_book'
  end
  namespace :for_user do
    resources :authors, only: [:index, :show]
    resources :books, only: [:index, :show]
    resources :bookings, only: [:index, :create, :destroy]
    get '/bookings/show/taken/books', to: 'books#show_taken_books', as: 'show_taken_books'
    get '/bookings/show/readed/books', to: 'books#show_readed_books', as: 'readed_books'
  end
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/views/user_books/index.html.erb
<div class='row' style='margin-bottom: 12px '>
  <div class='col col-md-3 '>
    <button type='button' class='btn btn-info btn-ms' data-toggle='modal' data-target='#myModal'>
      Filter
    </button>
  </div>
</div>
<div class='row'>
  <!-- Modal -->
  <div id='myModal' class='modal fade' role='dialog'>
    <div class='modal-dialog'>
      <!-- Modal content-->
      <div class='modal-content'>
        <div class='modal-header'>
          <button type='button' class='close' data-dismiss='modal'>&times;</button>
          <h4 class='modal-title'>Filter for books</h4>
        </div>
        <div class='modal-body'>
          <%= form_tag user_books_path, method: :get do %>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <a data-toggle='collapse' href='#collapse1'>Languages</a>
                  </h4>
                </div>
                <div id='collapse1' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @languages.each do |language| %>
                      <%= check_box_tag 'by_language_ids[]', language.id %>
                      <%= h language.language %>;
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <a data-toggle='collapse' href='#collapse2'>Authors</a>
                  </h4>
                </div>
                <div id='collapse2' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @authors.each do |author| %>
                      <%= check_box_tag 'by_authors_ids[]', author.id %>
                      <%= h author.name %>;
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='panel-group'>
              <div class='panel panel-default'>
                <div class='panel-heading'>
                  <h4 class='panel-title'>
                    <a data-toggle='collapse' href='#collapse3'>Categories</a>
                  </h4>
                </div>
                <div id='collapse3' class='panel-collapse collapse'>
                  <div class='panel-body'>
                    <% @categories.all.each do |categories| %>
                      <%= check_box_tag 'by_category_ids[]', categories.id %>
                      <%= h categories.title %>;
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class='row'>
              <div class='col-md-12'>
                <%= text_field_tag 'by_title_or_name_fo_author', params[:by_title_or_name_fo_author],
                                   placeholder: 'code\name_title\name_author',
                                   class: 'form-control col-md-6',
                                   style: 'width: 220px' %>
              </div>
            </div>
            </div>
            <div class='col-md-6'>
              <%= label_tag(:year, 'Year of release') %><br>
              <%= select_tag :by_year, options_for_select(@years, nil) %>

              <div><%= submit_tag 'Save' %></div>
            </div>

          <% end %>

          <div class='modal-footer'>
            <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
          </div>
          </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class='container-fluid cards-row'>
  <div class='row'>
    <% @books.each do |book| %>
      <div class='col-sm-6 col-md-4 article'>
        <div class='thumbnail' style='outline-style: solid; outline-radius: 7px; background-color: #ddaa68e6;'>
          <%= image_tag book.image_url, class: "img-responsive" if book.image_url %>
          <div class='caption'
               <% if @free_units_count[book] > 0 %> style='border-radius: 7px;background-color: #28a745a6;'
               <% else %>
               style='border-radius: 7px;background-color: #da7916b8;'
               <% end %>
               >
            <h3>Tile Of Book:
              <td><%= link_to book.title, user_book_path(book.id) %></td>
            </h3>
            <p class='card-description'>
              <strong>Author:  <%= book.author.name %></strong><br>
              <strong>Language:  <%= book.language.language %></strong><br>
              <strong>Rating:  <%= book.rating %></strong><br>
              <strong>Count of Free:</strong> <%= @free_units_count[book] %>\<%= book.units_count %></p>
            <% unless current_user %>
              <p>If you want do order you should to autorize</p>
            <% else %>
              <% if @free_units_count[book] > 0 %>
                <% if current_user.bookings.by_status(:taken).count < 4 %>
                  <% if current_user.bookings.by_status(:owed).count == 0 %>
                    <%= form_with url: user_bookings_path do |form| %>
                      <%= hidden_field_tag(:book_id, book.id) %>
                      <%= form.submit 'Do order', class: 'btn btn-success fa fa-check fa-1' %>
                    <% end %>

                  <% else %>
                    <p>You are debtor</p>
                  <% end %>
                <% else %>
                  <p>You have too much bookings</p>
                <% end %>
              <% else %>
                <p>Not have free books</p>
              <% end %>
            <% end %>
          </div>
          <%= @msg %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <% unless @books.empty? %>
        <%= paginate @books, outer_window: 3, class: "pagination" %>
      <% end %>
    </div>
  </div>
</div>

app/views/user_books/show_readed_books.html.erb
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default panel-table'>
      <div class='panel-heading'>
        <div class='row'>
          <div class='col col-md-6 text-right col-md-offset-3'>
            <div style='text-align: center'>
              <strong>
                Books that you read
              </strong>
            </div>
          </div>
        </div>
      </div>
      <div class='panel-body'>
        <table class='table table-striped table-bordered table-list'>
          <thead>
          <tr>
            <th>Title</th>
            <th>Year of release</th>
            <th>Catecory</th>
            <th>Author</th>
            <th>Description</th>
          </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to book.title, user_book_path(book.id) %></td>
              <td><%= link_to book.year, user_book_path(book.id) %></td>
              <td><%= link_to book.category.title, user_book_path(book.id) %></td>
              <td><%= link_to book.author.name, user_book_path(book.id) %></td>
              <td><%= link_to book.description[0..30] + '...', user_book_path(book.id) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/user_books/show_taken_books.html.erb
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default panel-table'>
      <div class='panel-heading'>
        <div class='row'>
          <div class='col col-md-6 text-right col-md-offset-3'>
            <div style='text-align: center'>
              <strong>
                Books that you take
              </strong>
            </div>
          </div>
        </div>
      </div>
      <div class='panel-body'>
        <table class='table table-striped table-bordered table-list'>
          <thead>
          <tr>
            <th>Title</th>
            <th>Year of release</th>
            <th>Catecory</th>
            <th>Author</th>
            <th>Description</th>
            <th>Start oreder this book:</th>
            <th>End oreder this book:</th>
            <th>before the end of the order days:</th>
          </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to book.title, user_book_path(book.id) %></td>
              <td><%= link_to book.year, user_book_path(book.id) %></td>
              <td><%= link_to book.category.title, user_book_path(book.id) %></td>
              <td><%= link_to book.author.name, user_book_path(book.id) %></td>
              <td><%= link_to book.description[0..30] + '...', user_book_path(book.id) %></td>
              <td><%= @books_booking[book].start_booking %></td>
              <td><%= @books_booking[book].end_booking %></td>
              <td><%= ((@books_booking[book].end_booking - DateTime.current) / 86400).to_i %> days</td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <% unless @books.empty? %>
              <%= paginate @books, outer_window: 3, class: "pagination" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>