config/routes.rb
Rails.application.routes.draw do
=begin
  get 'authors/index'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/show'
  get 'authors/destroy'
  get 'estimates/index'
  get 'estimates/new'
  get 'estimates/create'
  get 'estimates/update'
  get 'estimates/show'
  get 'estimates/destroy'
=end

  root to: 'for_user/books#index'
  devise_for :users

  resources :estimates

  namespace :api do
    post 'user_token' => 'user_token#create'
    resources :books, only: [:index]
    resources :authors, only: [:index, :show], param: :name
    resources :categories, only: [:index], param: :title
  end

  namespace :admin do
    resources :authors, only: [:index, :show, :new, :create, :update, :destroy]
    resources :users, only: [:index, :show, :update]
    resources :bookings, only: [:index, :new, :update, :destroy]
    resources :books, only: [:index, :show, :new, :create, :update, :destroy] do
      resources :units, only: [:destroy]
    end
    post '/bookings/update_bookings_statuses', to: 'bookings#update_bookings_statuses', as: 'update_bookings_statuses'
    post '/bookings/update_booking_status', to: 'bookings#update_booking_status', as: 'update_booking_status'
    post '/books/:book_id/units/add_one', to: 'units#create_unit_for_book', as: 'add_unit_book'
    post '/books/:book_id/recovery', to: 'books#recovery', as: 'recovery_book'
    # post '/books/:book_id/units/delete_last', to: 'units#delete_last_unit_for_book', as: 'delete_unit_book'
  end
  namespace :for_user do
    resources :authors, only: [:index, :show]
    resources :books, only: [:index, :show]
    resources :bookings, only: [:index, :create, :destroy]
    get '/bookings/show/taken/books', to: 'books#show_taken_books', as: 'show_taken_books'
    get '/bookings/show/readed/books', to: 'books#show_readed_books', as: 'readed_books'
  end
end

app/models/user.rb
class User < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :nullify
  has_many :estimates, dependent: :destroy
  has_many :books, through: :estimates
  # Devise really dislike knock onii-chan (>_<)
  # Necessary in order to use knox with devise
  alias authenticate valid_password?

  # Returns the for_user stored in the payload's subject
  def self.from_token_payload payload
    self.find payload["sub"]
  end

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}

  include Filterable
  scope :by_debtor, ->(by_debtor) {where(arel_table[:debtor].eq(by_debtor))}

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_user!, :user_admin!

    def index
      @users = User.filter(params.slice(:by_debtor)).page params[:page]
    end

    def show
      @user = User.find(params[:id])
      @bookings = @user.bookings
      @books_booking = {}
      @bookings.each {|booking| (@books_booking[booking] = booking.unit.book) if booking.unit}
    end

    def update
      @user = User.find(params[:user_id])
      @user.update(admin: params[:admin])
      redirect_to admin_user_path(@user)
    end

    def user_admin!
      redirect_to root_path unless current_user.admin
    end
  end
end

app/views/admin/users/index.html.erb
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default panel-table'>
      <div class='panel-heading'>
        <div class='row'>
          <%= form_tag admin_users_path, method: :get do %>
            <div class='row'>
              <div class='col-md-2' style='margin: 7px '>
                <%= select_tag :by_debtor, options_for_select([['Debtor', true], ['Not debtor', false], ['No filtre', ""]], '') %>
              </div>
              <div class='col-md-3'>
                <div><%= submit_tag 'Пошук', class: 'btn btn-ms btn-success ', style: 'margin-left: 5px;' %></div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class='panel-body table-responsive'>
        <table class='table table-striped table-bordered table-list'>
          <thead>
            <tr>
              <th><em class='fa fa-cog'></em></th>
              <th class='hidden-xs'>ID</th>
              <th class='hidden-xs'>Username</th>
              <th class='hidden-xs'>Email</th>
              <th class='hidden-xs'>Admin</th>
              <th class='hidden-xs'>Debtor</th>
            </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td align='center'>
                <!--                <%#= link_to new_book_path(book_id: book.id), class: ' btn btn-warning fa fa-pencil' do %>
                <%# end %>
                <%#= link_to book_path(book), method: :delete, data: {confirm: 'Are you sure?'}, class: ' btn btn-danger fa fa-trash' do %>
                <%# end %>-->
              </td>
              <td><%= link_to user.id, admin_user_path(user.id) %></td>
              <td><%= link_to user.username, admin_user_path(user.id) %></td>
              <td><%= link_to user.email, admin_user_path(user.id) %></td>
              <td><%= link_to admin_user_path(user.id) do %>
                  <%= user.admin ? 'Yes' : 'No' %>
                <% end %>
              </td>
              <td>  <%= user.debtor ? 'Yes' : 'No' %> </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <% unless @users.empty? %>
              <%= paginate @users, outer_window: 3, class: "pagination" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
<div class='row'>
  <div class='col-xs-12 col-sm-12 col-md-12 col-lg-12'>
    <div class='panel panel-info'>
      <div class='panel-heading'>
        <h3 class='panel-title'>
          Статистика користувача
        </h3>
      </div>
      <div class='panel-body'>
        <div class='row'>
          <div class='col-md-3 col-lg-3 ' align='center'>
            <% if @user.image_url %>
              <%= image_tag @user.image_url, class: "img-responsive" %>
              <% else %>
            <img alt='User Pic' src='http://localhost:3000/assets/book-shelves-book-stack-bookcase-207662.jpg' class='img-rounded img-responsive'>
              <% end %>
          </div>
          <div class='table-responsive'>
            <table class='table'>
              <tbody>
                <tr>
                  <td>Username:</td>
                  <td><%= @user.username %></td>
                </tr>
                <tr>
                  <td>Email:</td>
                  <td><%= @user.email %></td>
                </tr>
                <tr>
                  <td>Count of orders:</td>
                  <td><%= @bookings.count %></td>
                </tr>
                <tr>
                  <td>Debtor</td>
                  <td><%= @user.debtor %></td>
                </tr>
              </tbody>
            </table>
            <% if current_user.admin %>
              <% if @user.admin %>
                <%= form_with url: admin_user_path, method: :patch do |form| %>
                  <%= hidden_field_tag(:user_id, @user.id) %>
                  <%= hidden_field_tag(:admin, false) %>
                  <%#= form.submit 'Change on simple for_user', class: ' btn btn-sm btn-info ' %>
                  <%= form.submit 'Змінити на простого користувача', class: ' btn btn-sm btn-info ' %>
                <% end %>
              <% else %>
                <%= form_with url:  admin_user_path, method: :patch do |form| %>
                  <%= hidden_field_tag(:user_id, @user.id) %>
                  <%= hidden_field_tag(:admin, true) %>
                  <%= form.submit 'Змінити на адміністратора', class: 'btn btn-xs btn-success ' %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <!--            <div class='panel-footer'>
                    <a data-original-title='Broadcast Message' data-toggle='tooltip' type='button' class='btn btn-sm btn-primary'><i class='glyphicon glyphicon-envelope'></i></a>
                    <span class='pull-right'>
                      <a href='edit.html' data-original-title='Edit this for_user' data-toggle='tooltip' type='button' class='btn btn-sm btn-warning'><i class='glyphicon glyphicon-edit'></i></a>
                      <a data-original-title='Remove this for_user' data-toggle='tooltip' type='button' class='btn btn-sm btn-danger'><i class='glyphicon glyphicon-remove'></i></a>
                    </span>
               </div>-->
    </div>
  </div>
</div>

<div class='row'>
  <div class='col-md-12'>
    <div class='panel panel-default panel-table'>
      <div class='panel-heading'>
        <div class='row'>
          <div class='col col-md-6 text-right col-md-offset-3'>
            <div style='text-align: center'>
<!--              <strong>Your all bookings</strong>-->
              <strong>Всі замовлення користувача</strong>
            </div>
          </div>
        </div>
      </div>
      <div class='panel-body table-responsive'>
        <table class='table table-striped table-bordered table-list'>
          <thead>
            <tr>
<!--              <th class='hidden-xs'>ID</th>-->
<!--              <th class='hidden-xs'>Copy ID</th>-->
<!--              <th>Start Booking</th>-->
<!--              <th>End Booking</th>-->
<!--              <th>Status</th>-->
<!--              <th>User Name</th>-->
<!--              <th>Book Name</th>-->
<!--              <th>Author book</th>-->
              <th class='hidden-xs'>ID</th>
              <th class='hidden-xs'>Копія ID</th>
              <th>Покаток замовлення</th>
              <th>Кінець замовлення</th>
              <th>Статус замовлення</th>
              <th>Код</th>
              <th>Ім'я замовника</th>
              <th>Назва книги</th>
              <th>Ім'я автора</th>
            </tr>
          </thead>
          <tbody>
            <% @bookings.each do |booking| %>
              <tr>
                <% if @books_booking[booking] %>
                  <td><%= link_to booking.id, for_user_book_path(@books_booking[booking].id) %></td>
                  <td><%= link_to booking.unit_id, for_user_book_path(@books_booking[booking].id) %></td>
                  <td><%= link_to booking.start_booking, for_user_book_path(@books_booking[booking].id) %></td>
                  <td><%= link_to booking.end_booking, for_user_book_path(@books_booking[booking].id) %></td>
                  <td><%= link_to booking.status, for_user_book_path(@books_booking[booking].id) %></td>
                <% else %>
                  <td><%= booking.id %></td>
                  <td><%= booking.unit_id %></td>
                  <td><%= booking.start_booking %></td>
                  <td><%= booking.end_booking %></td>
                  <td><%= booking.status %></td>
                <% end %>
                <td><%= booking.code %></td>
                <td><%= booking.user.username %></td>
                <td><%= booking.book_title %></td>
                <td><%= booking.author_name %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>